debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.example.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

  jpa:
    database: mysql   # ?? ?? ??
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # ?? ?? ??
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  # h2 test ?? ??? ?
  #  h2.console.enabled: true
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true
  # h2 test ?? ??? ?
  #    url: jdbc:h2:mem:testdb
  #    username: sa
  #    driver-class-name: org.h2.Driver
  thymeleaf:
    check-template-location: false



---

spring:
  config.activate.on-profile: heroku





